steps:
- name: 'gcr.io/cloud-builders/git'
  id: 'Clone'
  args: ['clone', 'https://github.com/chinni4321/game-of-life.git']
- name: 'gcr.io/cloud-builders/mvn:3.3.9-jdk-8'
  args: ['install']
  dir: 'game-of-life/gameoflife-build/'
